name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_release:
    name: Build for Multiple Platforms and Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Build for Linux, Windows, macOS
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o release/gama-linux-amd64 cmd/main.go
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o release/gama-windows-amd64.exe cmd/main.go
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o release/gama-macos-amd64 cmd/main.go
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-s -w" -o release/gama-macos-arm64 cmd/main.go

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/gama-linux-amd64,release/gama-windows-amd64.exe,release/gama-macos-amd64,release/gama-macos-arm64"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
