name: Update Version

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Update Version in main.go
        run: |
          sed -i "s/var.*Version.*/var Version = \"${{ inputs.version }}\" \/\/ will be set by build flag/g" main.go

      - name: Run Go fmt
        run: go fmt main.go

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add main.go
          git commit -m "Update version to ${{ inputs.version }}"
          git push
